name: GitHub Actions Auto Health Report
on:
  # Run script on daily 10:00am
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: |
          python report.py -m manual -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
